bitfinexcom/sunbeam

lib/order.js
package.json
test/browser-exchange/jsx/app.jsx
test/ws-stub/server.js
test/ws-stub/stream.js

the server simulates order activity on the btc.usd book. order
have a lifetime of 5sec to 2min, until they are cancelled or
filled

 ws: add small mock server

---

example-ws.js
lib/mandelbrot-ws-base.js
lib/sunbeam-ws.js

- adds snapshot detection and raw orderbook handling to sunbeam
- uses the R0 orderbook format

add raw orderbook transforms

---

example-ws.js
lib/mandelbrot-ws-base.js
lib/sunbeam-ws.js

stays in line with orderbook management

wallet: unify onWalletUpdate and onWalletSnapshot

---

example-ws.js
index.js
lib/managed-ob.js
lib/mandelbrot-ws-base.js
lib/sunbeam-ws.js
test/orderbook.js

orderbooks: add pluggable managed books
- provides on the fly parsing and managed state
- managed wallet updates now even with no handler set, given a
handler is after the initial snapshot was sent
expose managed Wallet and Orderbook for standalone usage
info msg parser: fix changed channel id

improved pluggable managed orderbook handling

---

README.md
example-orderbook.js
example-wallet.js

depends on: https://github.com/bitfinexcom/sunbeam/pull/26

examples: usage examples for standalone components

---

example-ws.js
lib/mandelbrot-ws-base.js

- adds convenience method for orderbooks

channels: add unsubscribe handlers

---

lib/index-legacy.js
lib/index.js
package.json

- import with: `require('sunbeam/dist/legacy.js')`

build: re-enable legacy http

---

example-ws.js
lib/http-order-sign.js
lib/sunbeam-ws.js

Usage:
```js
ws.cancel({
symbol: 'BTC.USD',
id: '1'
})
```

 add signed order cancel

---

lib/order.js
test/orders.js

fixes float32 issue with multiply by 10000

 orders: fix float point issue

---

example-ws.js
lib/managed-orders.js
lib/mandelbrot-ws-base.js
lib/sunbeam-ws.js
test/order.js
test/orders.js

takes snapshots and keeps them up to date.

orders: add managed orders

---

README.md
example-orders.js

- example: add orders
- docs: flesh out docs

docs / examples

---

example-ws.js
lib/mandelbrot-ws-base.js

```js
sb.unSubscribeOrders()
```

order updates: add unsubscribe method

---

example-ws.js
lib/order.js
test/order.js

depends on https://github.com/bitfinexcom/sunbeam/pull/52

add sugar for ioc orders

---

README.md
example-ws.js
lib/mandelbrot-ws-base.js
lib/sunbeam-ws.js

usage:
```js
ws.onTrades({ symbol: 'ETH.USD' }, (data) => {
console.log('ws.onTrades({ symbol: "ETH.USD" }')
console.log(data) // emits [ 'ETH.USD', 'te', [ '3', 1537196302500, -0.9, 1 ] ]
})
ws.subscribeTrades('ETH.USD')
```

add public trade handlers

---

README.md
example-ws.js
lib/sunbeam-ws.js

Usage:
```js
ws.sweep({
currency: 'EUR'
})
```

 add pre-signed sweep 

---

README.md
example-ws.js
lib/http-order-sign.js
lib/sunbeam-ws.js

presigns transfer with forked eosio.token contract efinextether
Usage:
```js
ws.deposit({
currency: 'EUR',
amount: '2'
})
```

 add deposit method

---

package.json

also precopile deps like cbqjs

build: pre-compile all dependencies

---

example-scatter.js
example-ws.js

fixed via https://github.com/GetScatter/scatter-js/issues/47

examples: scatter brings isomorphic js now

---

README.md
example-scatter.js
example-ws.js
lib/order-sign.js
lib/sunbeam-ws.js
package.json

sends a transaction to the websocket plugin which is just
validated, not applied

 history via http support

---

example-orderbook.js
example-wallet.js
test/int-sub-unsub-ob.js

better to move to userland, it requires bigint support, and
polyfills/libraries should stay optional.

decimals: remove undocumented feature

---

example-orders.js
example-wallet.js
example-ws.js
lib/managed-orders.js
test/orders.js

 orders: add oc message support

---

README.md
example-scatter.js
example-ws.js
lib/order-sign.js
lib/scatter.js
lib/sunbeam-ws.js
lib/util.js
package.json

- supports the new 2.x release of eos js
- moves scatter hlper functions to own class

port to eosjs@20.x

---

lib/scatter.js
lib/sunbeam-ws.js

+ syntax fix for bad fix in #114

scatter: custom auth options pass through

---

README.md

document language agnostic responses of ws api

document order book responses

---

lib/managed-orders.js
package.json

orders: fix snapshots

---

lib/sunbeam-ws.js

additional changes:
- adds `setMaxListeners` delegate method

connect: register events once

---

package.json

Update mandelbrot on mainnet to `master` branch.

(chore) update mandelbrot to  master branch

---

package.json

i remove this task for working locally. Because it doesn't work on windows.
accidentially pushed the changes

(fix) add prepare task
