bitfinexcom/sunbeam

- example-ws.js
- lib/managed-wallet.js
- lib/mandelbrot-ws-base.js
- lib/sunbeam-ws.js
- test/wallets.js
small pluggable wallet mananager that manages wallet state
coming from snapshots and update messages
usage:
```js
ws.onManagedWalletUpdate({}, (mw) => {
console.log('ws.onManagedWalletUpdate')
console.log(mw)
})
```
> wallet: adds managed wallet

- example-ws.js
- lib/managed-ob.js
- lib/managed-wallet.js
- lib/mandelbrot-ws-base.js
- lib/sunbeam-ws.js
- test/wallets.js
decimals support for wallet.
in eosfinex, the default is 8 decimals for wallet data, while the orderbook uses 4 decimals.
see f4333fe for enabling 8 decimals in `example-ws.js`
- includes a small reference / deep clone fix for orderbooks
>  wallets: support decimal transforms

- lib/mandelbrot-ws-base.js
- lib/sunbeam-ws.js
- test/int-sub-unsub-ob.js
- test/read-write-node.js
- test/ws-testhelper.js
init: make Eos lib optional  
- helps with testing or with smaller builds that do not need
order signing
test: verify that state is handled between subscriptions
- also removes channels from subscription list
> small improvements + test coverage

- example-wallet.js
- lib/managed-wallet.js
- test/wallets.js
format is now:
```
[ '0',
'ws',
[ [ 'exchange', 'USD', 98.999, 0, 98.999 ],
[ 'exchange', 'ETH', 100, 0, 100 ],
[ 'exchange', 'EUR', 100, 0, 100 ],
[ 'exchange', 'EOS', 100, 0, 100 ],
[ 'exchange', 'BTC', 92.996, 0, 92.996 ] ] ]
[ '0', 'wu', [ 'exchange', 'USD', 99.997, 0, null ] ]
> wallets: apply format changes

- example-ws.js
- lib/mandelbrot-ws-base.js
this will emit messages like `oc`, so the ui can show error
messages.
usage example:
```js
// emits all updates
ws.onOrderUpdate({}, (data) => {
console.log('ws.onOrderUpdate({}')
console.log(data)
})
// filter enabled
ws.onOrderUpdate({ symbol: 'BTC.USD' }, (data) => {
console.log('ws.onOrderUpdate({ symbol: "BTC.USD" }')
console.log(data)
})
```
example:
```js
[ '0',
'oc',
[ '0',
0,
1536169530413,
'BTC.USD',
1536169531,
0,
0,
1,
'testuser1554',
'no.market' ] ]
```
> order updates: add filtered listener

- example-http.js
- example-ws.js
- lib/sunbeam-ws.js
- lib/sunbeam.js
- @active stays default permission level
- adds ability to set own permission levels
docs: https://developers.eos.io/eosio-nodeos/docs/accounts-and-permissions
> permissions: make permission level configurable

- lib/order.js
- test/order.js
this abstraction is useful when building ui's that connect to
different endpoints which use different flags.
>  add postOnly property to orders

- README.md
- lib/mandelbrot-ws-base.js
- lib/sunbeam-ws.js
`to` property is optional, defaults to account.
```js
ws.withdraw({
currency: 'EUR',
amount: '0.678'
})
```
---
included:
docs: add cancel argument properties
small refactor:
- unsubscribe orders: stub in base, implement in sb
>  withdraw: add widthdraw action

- README.md
- example-prefetched-abi-ws.js
- lib/http-order-sign.js
this removes the requirement for initial http calls to an eos node,
so in the future, sunbeam is able to run on ws only, if needed.
>  add feature to prefetch contract abis

- README.md
- lib/order-sign.js
- lib/sunbeam-ws.js
- package.json
gets the required data for tx signing from the websocket instead
of an eos node http endpoint.
> sign: receive metadata for tx headers from websocket

- lib/mandelbrot-ws-base.js
message without subscription would throw an error, e.g.
`[ '', [] ]`
> do not crash on invalid message

- README.md
- example-prefetched-abi-ws.js
- example-scatter.js
- example-ws.js
- lib/order-sign.js
- lib/sunbeam-ws.js
- package.json
other changes:
-  added `logoutScatter()`to end scatter session 
- all async methods to create transactions return a promise now,
e.g. `place()`, `cancel()` [...] the promise resolves with the
sent payload and the data:
```js
const { payload, data } = await ws.place(order)
console.log(data.clientId) // use in cancel method
```
this is also useful for error handling.
- `auth()` returns a Promise now
- `getChainId()` is a new method to retrieve the chain id, which
is then cached for later use. internally used for the scatter
auth flow.
> scatter support: support scatter for auth

- lib/order-sign.js
- lib/sunbeam-ws.js
- package.json
The URL require was failing in browsers, this PR flips the check around and removes the browserify url shim (reducing dist size from 185k to 140k)
> Fix require URL for browsers

- README.md
- lib/sunbeam-ws.js
it signs a verification transaction that is send to the
Websocket endpoint for validation. This transaction is not applied
to the chain, just used for verifying the signature.
> auth: sign verification transaction

- lib/sunbeam-ws.js
Previously errors were not reported as the await would error inside the promise call method. I've updated this method to look like the others.
@robertkowalski is there a reason we wrap these methods with a promise, could they not be async methods that return the resolved value?
> Fix auth call preventing errors

- README.md
- lib/managed-orders.js
- test/orders.js
does not delete cancelled orders (`oc`) from the state and marks
them as deleted
> orders: add markDeleted feature

- lib/sunbeam-ws.js
When using 'Connect with Scatter' I got an error like:
> {type: "bad_network", message: "The network being suggested is invalid", code: 423, isError: true}
If the given endpoint URL didn't have a specified port, no port would be given to the scatter endpoint. Which resulted in the above error.
(at least on my local Windows machine + jeffrey.lozier reported it. Doesn't seem to have been a general issue for everyone...?).
Made a fix, where it will assume the port number based on the protocol, if no port has been explicitly set.
> Fixed so a default port is suggested if one is not explicitly set

- lib/sunbeam-ws.js
uuid has to be part of the namespace, fixes a race condition were
just the first response was valid
> verify-tx: fix uuid/ns issue

- lib/order-sign.js
time out connection in case we don't get a response for signing,
e.g. when using wrong urls or when the backend is down.
> tx signing: use request timeout for tx signing, too

- lib/order-sign.js
- lib/sunbeam-ws.js
- scatter requests often take longer, removing the timeout again
- when no account in scatter was found, return with an error
> scatter: remove request timeouts

- lib/sunbeam-ws.js
- lib/util.js
- test/int-sub-unsub-ob.js
- test/util.js
`DecimalString` in eosjs@16 is removing trailign zeros, which is
required for `Decimalpad` to calculate the proper padding for
values with trailing zeros, i.e. `98.3000`.
>  decimalPad: add DecimalString from eosjs@16

- lib/sunbeam-ws.js
this change allows authentication configuration to be added after
sunbeam is instantiated
---
rebased & standard linted version of #104
> allow auth config to be passed to auth method

- lib/scatter.js
Move `suggestNetwork` before `hasAccountFor` check to prevent error from `hasAccountFor` if the network does not exist in Scatter.
> scatter: suggest network before checking account

- lib/scatter.js
Remove `scatter.forgetIdentity` to prevent already selected identity from being reset when logging in
> scatter: remove forgetIdentity from login

- lib/scatter.js
adds a request to `scatter.forgetIdentity` after scatter connection has been established.
> scatter: add forgetIdentity after initial connection

- README.md
- example-scatter.js
- lib/sunbeam-ws.js
- package.json
signed transactions are used as auth mechanism for different
things: tos handling, trade history and websocket auth.
in the future, probably more endpoints are going to be added.
for auth mechanism like scatter, this means right now, that a login
to the ui needs multiple transactions signed by the user, which
results in a bad ux.
to provide maximum flexibilty in the future, this removes
the built-in moonbeam request wrapper. a client can request a
tx with `getSignedTx` now, that can be used for their tos, ws-auth
and history handling, until the tx expires by the defined
timeframe.
> factor out history support, add `getSignedTx` helper

- .gitignore
- README.md
- config/example-ws.config.json.example
- example-ws.js
- lib/sunbeam-ws.js
- package.json
- test/int-sub-unsub-ob.js
- breaking changes:
- init of sunbeam takes other options now (regardigng `urls`: for old api, use thrree times the same url)
- because the websocket adapter had to get decoupled from the state, the message handlers had to get rewritten. with the rewrite i unified the format for the `onXy` handlers
- `subscribe`, `send`, `unsubscribe`  etc need a transport hint now, example: `ws.send('priv', { event: 'pa' }}`
- docs updates
> websockets: support multiple connections

- config/example-ual.config.json.example
- config/example-ws.config.json.example
- example-ws.js
- lib/order-sign.js
- lib/sunbeam-ws.js
- test/order.js
added `updateKey` method
requires `account` and `pubkey` to be passed. `permission` is optional, defaults to `active`
see `example-ws.js` for the example. Eosjs API instance needs to be modified to support partial signature, which is most probably already done because of `reguser`
> change key initial implementation

- lib/order-sign.js
- lib/order.js
- lib/sunbeam-ws.js
Pass either `expire` and other tx header part or `blocksBehind` + `expireSeconds`. Due to [this](https://github.com/EOSIO/eosjs/blob/20.0.0/src/eosjs-api.ts#L223) logic in the eosjs library, either TAPOS or `blocksBehind` + `expireInSeconds` make sense. In addition to that, TAPOS generated with regards to the head block while `expireInSeconds` takes `blocksBehind` into consideration.
> correct transaction expiration time

- config/example-ual.config.json.example
- config/example-ws.config.json.example
- lib/order-sign.js
- lib/order.js
- lib/sunbeam-ws.js
- package.json
- test/order.js
* Omit chain meta request when `expireInSeconds` is used. `eosjs` calculates it internally no matter what.
* Tie expiration time to the transaction / order type. Remove it from config
* EXCHANGE LIMIT expiration time = head block time + 7 days
* EXCHANGE LIMIT + tif expiration time = tif + 1 day
* all other cases (new orders, deposit, etc) = head block time + 1 day
> compute expiration time based on type of the order

- lib/order-sign.js
- lib/sunbeam-ws.js
- lib/util.js
Issue description:
`ual-anchor` doesn't take transaction options like `expireSeconds` or `blocksBehind` into account. Tapos fields should be included in the transaction in order to set expiration time
* [signTransaction](https://github.com/greymass/ual-anchor/blob/master/src/AnchorUser.ts#L38) calls [transact](https://github.com/greymass/anchor-link/blob/9e8df0941feeba185356cdeb5786a6ab6ab43126/src/link.ts#L299), which takes only `broadcast` into account
* then, [createRequest](https://github.com/greymass/anchor-link/blob/9e8df0941feeba185356cdeb5786a6ab6ab43126/src/link.ts#L182) is called, which calls [create](https://github.com/greymass/eosio-signing-request/blob/master/src/signing-request.ts#L245). Options param is not used anywhere, except to retrieve `broadcast` flag
* …
> compute tapos fields, use last irreversible block
